"""
Holiday Resolver Engine — Python port of holiday-resolver.js

Resolves holiday occurrences from RRULE-based schedules, applies observance
shifting rules, and evaluates operational / network impacts for a given year.

Usage:
    from holiday_resolver import HolidayResolver
    import json

    with open('sample-config.json') as f:
        config = json.load(f)

    resolver = HolidayResolver(config)
    events   = resolver.resolve(2026)
    result   = resolver.check_date('2026-07-03')
"""

from __future__ import annotations

import re
from calendar import monthrange
from dataclasses import dataclass, field, asdict
from datetime import date, timedelta
from typing import Any

# ── Weekday mappings ─────────────────────────────────────────────────────────
# Python date.weekday(): Mon=0 … Fri=4, Sat=5, Sun=6
# RRULE BYDAY codes:     MO, TU, WE, TH, FR, SA, SU

WD: dict[str, int] = {
    'MO': 0, 'TU': 1, 'WE': 2, 'TH': 3, 'FR': 4, 'SA': 5, 'SU': 6,
}
# Index by Python weekday() to get RRULE short code
WD_SHORT = ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU']
WD_FULL  = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
             'Friday', 'Saturday', 'Sunday']
MONTH_FULL = [
    '', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
]

# ── Date utilities ────────────────────────────────────────────────────────────

def to_date_str(d: date) -> str:
    return d.isoformat()


def parse_date(s: str) -> date:
    return date.fromisoformat(s)


def add_days(d: date, n: int) -> date:
    return d + timedelta(days=n)


def is_weekend(d: date) -> bool:
    return d.weekday() >= 5  # Sat=5, Sun=6


def prev_business_day(d: date) -> date:
    d = add_days(d, -1)
    while is_weekend(d):
        d = add_days(d, -1)
    return d


def next_business_day(d: date) -> date:
    d = add_days(d, 1)
    while is_weekend(d):
        d = add_days(d, 1)
    return d


def format_date_long(date_str: str) -> str:
    """Return e.g. 'Friday, January 1, 2026'."""
    d = parse_date(date_str)
    return f"{WD_FULL[d.weekday()]}, {MONTH_FULL[d.month]} {d.day}, {d.year}"


# ── RRULE parser / expander ──────────────────────────────────────────────────

class RRuleParser:
    """
    Expands RRULE strings (FREQ=YEARLY subset) into concrete date instances
    for a given calendar year.

    Supported parts: FREQ, BYMONTH, BYMONTHDAY, BYDAY (with nth prefix),
                     BYSETPOS, UNTIL, INTERVAL (gating only), RDATE, EXDATE.
    """

    @staticmethod
    def parse(rrule_str: str) -> dict[str, str]:
        rule: dict[str, str] = {}
        for part in rrule_str.strip().split(';'):
            if '=' in part:
                k, v = part.split('=', 1)
                rule[k.upper()] = v
        return rule

    @staticmethod
    def expand_for_year(rrule_str: str, year: int) -> list[date]:
        """Return all dates generated by *rrule_str* that fall in *year*."""
        rule = RRuleParser.parse(rrule_str)

        freq = rule.get('FREQ', 'YEARLY')
        if freq != 'YEARLY':
            import warnings
            warnings.warn(
                f"[RRuleParser] FREQ={freq} is not fully supported; "
                "treating as YEARLY.",
                stacklevel=2,
            )

        # UNTIL gate
        if 'UNTIL' in rule:
            raw = rule['UNTIL']
            # Normalise YYYYMMDD[T...] → YYYY-MM-DD
            raw = re.sub(r'T.*$', '', raw)
            if len(raw) == 8:
                raw = f"{raw[:4]}-{raw[4:6]}-{raw[6:8]}"
            if parse_date(raw).year < year:
                return []

        months_raw = rule.get('BYMONTH')
        months = (
            [int(m) for m in months_raw.split(',')]
            if months_raw
            else list(range(1, 13))
        )

        results: list[date] = []

        for month in months:
            days_in_month = monthrange(year, month)[1]

            # ── BYMONTHDAY ────────────────────────────────────────────────
            if 'BYMONTHDAY' in rule:
                for raw in rule['BYMONTHDAY'].split(','):
                    day_num = int(raw)
                    if day_num < 0:
                        day_num = days_in_month + day_num + 1
                    if 1 <= day_num <= days_in_month:
                        results.append(date(year, month, day_num))

            # ── BYDAY ─────────────────────────────────────────────────────
            elif 'BYDAY' in rule:
                candidates: list[date] = []

                for byday in rule['BYDAY'].split(','):
                    m = re.match(r'^(-?\d*)([A-Z]{2})$', byday)
                    if not m:
                        continue
                    n  = int(m.group(1)) if m.group(1) else 0
                    wd = WD.get(m.group(2))
                    if wd is None:
                        continue

                    if n == 0:
                        # Every occurrence of this weekday in the month
                        for day in range(1, days_in_month + 1):
                            d = date(year, month, day)
                            if d.weekday() == wd:
                                candidates.append(d)

                    elif n > 0:
                        # nth from start
                        first  = date(year, month, 1)
                        offset = (wd - first.weekday()) % 7
                        day_num = 1 + offset + (n - 1) * 7
                        if day_num <= days_in_month:
                            candidates.append(date(year, month, day_num))

                    else:
                        # nth from end (negative n)
                        last   = date(year, month, days_in_month)
                        offset = (last.weekday() - wd) % 7
                        day_num = days_in_month - offset + (n + 1) * 7
                        if 1 <= day_num <= days_in_month:
                            candidates.append(date(year, month, day_num))

                if 'BYSETPOS' in rule:
                    candidates.sort()
                    for pos_str in rule['BYSETPOS'].split(','):
                        pos = int(pos_str)
                        idx = (pos - 1) if pos > 0 else (len(candidates) + pos)
                        if 0 <= idx < len(candidates):
                            results.append(candidates[idx])
                else:
                    results.extend(candidates)

            else:
                # Only BYMONTH with no day spec — default to 1st of month
                results.append(date(year, month, 1))

        return results


# ── HolidayResolver ──────────────────────────────────────────────────────────

class HolidayResolver:
    """
    Main resolver.  Accepts a configuration dict that follows the schema
    defined by the class diagram (Jurisdiction, HolidayEvent, Policy,
    Impact, …).
    """

    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.jurisdictions: dict[str, dict] = {
            j['id']: j for j in config.get('jurisdictions', []) if 'id' in j
        }
        self.events: dict[str, dict] = {
            e['id']: e for e in config.get('events', []) if 'id' in e
        }
        self.policies: dict[str, dict] = {
            p['id']: p for p in config.get('policies', []) if 'id' in p
        }
        self.impacts: list[dict] = config.get('impacts', [])

    # ── public API ────────────────────────────────────────────────────────

    def resolve(
        self,
        start_year: int,
        end_year: int | None = None,
        jurisdiction_id: str | None = None,
    ) -> list[dict]:
        """
        Resolve all holiday events for *start_year* through *end_year*
        (inclusive).  Optionally filter by *jurisdiction_id* (includes all
        child jurisdictions).

        Returns a list of resolved-event dicts sorted by observed_date.
        """
        if end_year is None:
            end_year = start_year

        scope = (
            self._jurisdiction_scope(jurisdiction_id)
            if jurisdiction_id
            else None
        )

        results: list[dict] = []
        for year in range(start_year, end_year + 1):
            for event in self.events.values():
                if scope:
                    jur = self.jurisdictions.get(event.get('jurisdiction_id', ''))
                    if not jur or jur['id'] not in scope:
                        continue
                results.extend(self._resolve_event(event, year))

        results.sort(key=lambda e: e['observed_date'])
        return results

    def check_date(
        self,
        date_str: str,
        jurisdiction_id: str | None = None,
    ) -> dict:
        """
        Check whether *date_str* (YYYY-MM-DD) is a holiday (actual or
        observed) in the given jurisdiction.
        """
        year = int(date_str[:4])
        all_events = self.resolve(year, year, jurisdiction_id)
        matches = [
            e for e in all_events
            if e['actual_date'] == date_str or e['observed_date'] == date_str
        ]
        return {
            'date':        date_str,
            'is_holiday':  bool(matches),
            'is_actual':   any(e['actual_date']   == date_str for e in matches),
            'is_observed': any(e['observed_date'] == date_str for e in matches),
            'events':      matches,
        }

    # ── jurisdiction scope ────────────────────────────────────────────────

    def _jurisdiction_scope(self, jur_id: str) -> set[str]:
        """Return the set of jurisdiction IDs that are *jur_id* or descendants."""
        scope = {jur_id}
        changed = True
        while changed:
            changed = False
            for jid, jur in self.jurisdictions.items():
                if jid not in scope and jur.get('parent_id') in scope:
                    scope.add(jid)
                    changed = True
        return scope

    # ── event resolution ──────────────────────────────────────────────────

    def _resolve_event(self, event: dict, year: int) -> list[dict]:
        td = event.get('time_definition')
        if not td:
            return []

        recurrence = td.get('recurrence')
        dates: list[date] = []

        if not recurrence:
            if 'start_date' in td:
                d = parse_date(td['start_date'])
                if d.year == year:
                    dates.append(d)
        else:
            try:
                dates = RRuleParser.expand_for_year(recurrence['rrule'], year)
            except Exception as exc:
                import warnings
                warnings.warn(
                    f"[HolidayResolver] RRULE error for '{event['id']}': {exc}",
                    stacklevel=2,
                )
                return []

            # RDATE — additional explicit dates
            for rd in recurrence.get('rdate', []):
                d = parse_date(rd)
                if d.year == year:
                    dates.append(d)

            # EXDATE — exclusions
            exdates = {
                to_date_str(parse_date(ex))
                for ex in recurrence.get('exdate', [])
            }
            dates = [d for d in dates if to_date_str(d) not in exdates]

        obs_rules = recurrence.get('observance_rules', []) if recurrence else []
        return [
            self._build_result(event, actual, self._apply_observance(actual, obs_rules), year)
            for actual in dates
        ]

    def _apply_observance(self, d: date, rules: list[dict]) -> date:
        wd = d.weekday()  # 0=Mon … 5=Sat, 6=Sun
        for rule in rules:
            cond   = rule.get('condition', '')
            action = rule.get('action', '')
            hit = (
                (cond == 'falls_on_saturday'  and wd == 5) or
                (cond == 'falls_on_sunday'    and wd == 6) or
                (cond == 'falls_on_weekend'   and wd >= 5)
            )
            if not hit:
                continue
            if action == 'observe_previous_business_day':
                return prev_business_day(d)
            if action == 'observe_next_business_day':
                return next_business_day(d)
            if action == 'no_observance_shift':
                return d
        return d

    def _build_result(
        self, event: dict, actual: date, observed: date, year: int,
    ) -> dict:
        actual_str   = to_date_str(actual)
        observed_str = to_date_str(observed)
        jur = self.jurisdictions.get(event.get('jurisdiction_id', ''))

        return {
            'id':             event['id'],
            'name':           event['name'],
            'classification': event.get('classification'),
            'status':         event.get('status'),
            'alt_names':      event.get('alt_names', []),
            'jurisdiction':   jur,
            'actual_date':    actual_str,
            'observed_date':  observed_str,
            'is_shifted':     actual_str != observed_str,
            'shift_direction': (
                'forward' if observed > actual else 'back'
            ) if actual_str != observed_str else None,
            'year':           year,
            'impacts':        self._resolve_impacts(event, actual, observed),
            'daily_windows':  event.get('time_definition', {}).get('daily_windows', []),
        }

    # ── impact resolution ─────────────────────────────────────────────────

    def _resolve_impacts(
        self, event: dict, actual: date, observed: date,
    ) -> list[dict]:
        return [
            self._evaluate_impact(imp, actual, observed)
            for imp in self.impacts
            if self._matches_event(imp.get('match', {}), event)
        ]

    def _matches_event(self, match: dict, event: dict) -> bool:
        if not match:
            return False
        if match.get('event_id') and match['event_id'] != event['id']:
            return False
        if match.get('id') and match['id'] != event['id']:
            return False
        jur = self.jurisdictions.get(event.get('jurisdiction_id', ''))
        if match.get('iso_3166_1') and (
            not jur or jur.get('iso_3166_1') != match['iso_3166_1']
        ):
            return False
        if match.get('iso_3166_2') and (
            not jur or jur.get('iso_3166_2') != match['iso_3166_2']
        ):
            return False
        if match.get('policy_id'):
            return False  # policy impacts are handled separately
        return True

    def _evaluate_impact(
        self, impact: dict, actual: date, observed: date,
    ) -> dict:
        entries: list[dict] = []
        schedule = impact.get('impact_schedule')
        if schedule:
            tz = schedule.get('timezone')
            for op in schedule.get('operations', []):
                for rule in op.get('rules', []):
                    entry = self._eval_impact_rule(
                        rule, op['operation'], actual, observed, tz,
                    )
                    if entry is not None:
                        entries.append(entry)
        return {
            'operational_impact': impact.get('operational_impact'),
            'network_impacts':    impact.get('network_impacts'),
            'schedule_entries':   entries,
        }

    def _eval_impact_rule(
        self,
        rule: dict,
        operation: str,
        actual: date,
        observed: date,
        tz: str | None,
    ) -> dict | None:
        when = rule.get('when')
        if not when:
            return None

        base   = actual if when.get('date_ref') == 'actual' else observed
        target = add_days(base, when.get('offset_days', 0))

        # Evaluate ConditionBlock
        cond = rule.get('if')
        if cond:
            weekday_in = cond.get('weekday_in')
            if weekday_in:
                wd_code = WD_SHORT[target.weekday()]
                if wd_code not in weekday_in:
                    return None

        return {
            'operation':   operation,
            'date':        to_date_str(target),
            'date_ref':    when.get('date_ref'),
            'offset_days': when.get('offset_days', 0),
            'effect':      rule.get('effect'),
            'reason':      rule.get('reason'),
            'condition':   cond,
        }


# ── PolicyResolver ────────────────────────────────────────────────────────────

class PolicyResolver:
    """Resolves policy schedules (same RRULE expansion, different schema)."""

    def __init__(self, config: dict[str, Any]) -> None:
        self.jurisdictions: dict[str, dict] = {
            j['id']: j
            for j in config.get('jurisdictions', [])
            if 'id' in j
        }
        self.policies: dict[str, dict] = {
            p['id']: p
            for p in config.get('policies', [])
            if 'id' in p
        }

    def resolve(self, year: int) -> list[dict]:
        results: list[dict] = []
        for policy in self.policies.values():
            td = policy.get('time_definition', {})
            rec = td.get('recurrence')
            if not rec:
                continue
            try:
                dates = RRuleParser.expand_for_year(rec['rrule'], year)
            except Exception:
                continue
            for d in dates:
                results.append({
                    'id':       policy['id'],
                    'name':     policy['name'],
                    'category': policy.get('category'),
                    'status':   policy.get('status'),
                    'date':     to_date_str(d),
                    'year':     year,
                })
        results.sort(key=lambda p: p['date'])
        return results


# ── CLI helper ────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    import json
    import sys

    config_path = sys.argv[1] if len(sys.argv) > 1 else 'sample-config.json'
    year        = int(sys.argv[2]) if len(sys.argv) > 2 else 2026

    with open(config_path) as f:
        cfg = json.load(f)

    resolver = HolidayResolver(cfg)
    events   = resolver.resolve(year)

    print(f"\n{'─'*64}")
    print(f"  Resolved {len(events)} holidays for {year}")
    print(f"{'─'*64}\n")

    for ev in events:
        shift = ''
        if ev['is_shifted']:
            shift = f"  (actual: {ev['actual_date']} → {ev['shift_direction']})"
        jur = ev['jurisdiction']
        jur_tag = f"[{jur.get('iso_3166_2') or jur.get('iso_3166_1') or jur['id']}]" if jur else ''
        max_level = 'none'
        for imp in ev['impacts']:
            lvl = (imp.get('operational_impact') or {}).get('impact_level', '')
            order = {'full': 3, 'conditional': 2, 'partial': 1, 'none': 0}
            if order.get(lvl, -1) > order.get(max_level, -1):
                max_level = lvl
        print(f"  {ev['observed_date']}  {jur_tag:<8}  {ev['name']:<42}  [{max_level}]{shift}")

    print()
